## Loading the dataset

In [1]:
#!pip install sentence_transformers

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
import pandas as pd
import numpy as np
import ast

In [4]:
# Set the maximum column width to 100 characters
pd.set_option('display.max_colwidth', 500)

In [5]:
books_df = pd.read_csv('books.csv')

In [6]:
books_df.head(10)

,book_name,summaries
0,The Highly Sensitive Person,"is a self-assessment guide and how-to-live template for people who feel, relate, process, and notice more deeply than others, and who frequently suffer from overstimulation as a result."
1,Why Has Nobody Told Me This Before?,"is a collection of a clinical psychologist’s best practical advice to combat anxiety and depression and improve our mental health in small increments, collected from over a decade of 1-on-1 work with patients."
2,The Midnight Library,"tells the story of Nora, a depressed woman in her 30s, who, on the day she decides to die, finds herself in a library full of lives she could have lived, where she discovers there’s a lot more to life, even her current one, than she had ever imagined."
3,Brave New World,"presents a futuristic society engineered perfectly around capitalism and scientific efficiency, in which everyone is happy, conform, and content — but only at first glance."
4,1984,is the story of a man questioning the system that keeps his futuristic but dystopian society afloat and the chaos that quickly ensues once he gives in to his natural curiosity and desire to be free.
5,Stolen Focus,"explains why our attention spans have been dwindling for decades, how technology accelerates this worrying trend, and what we can do to reclaim our focus and thus our capacity to live meaningful lives."
6,The Life-Changing Science of Detecting Bullshit,teaches its readers how to avoid falling for the lies and false information that other people spread by helping them build essential thinking skills through examples from the real world.
7,Dopamine Nation,"talks about the importance of living a balanced life in relation to all the pleasure and stimuli we’re surrounded with on a daily basis, such as drugs, devices, porn, gambling facilities, showing us how to avoid becoming dopamine addicts by restricting our access to them."
8,The Art of Statistics,"is a non-technical book that shows how statistics is helping humans everywhere get a new hold of data, interpret numbers, fact-check information, and reveal valuable insights, all while keeping the world as we know it afloat."
9,No Self No Problem,"is a provocative read about the implications of Buddhism in neuroscience, and more specifically about the idea that the self is only a product of the mind, meaning that there is no “I”."

In [7]:
books_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1227 entries, 0 to 1226
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   book_name  1227 non-null   object
 1   summaries  1227 non-null   object
dtypes: object(2)
memory usage: 19.3+ KB

In [8]:
books_df.shape

(1227, 2)

## Embedding Model

In [9]:
from sklearn.metrics.pairwise import cosine_similarity
from sentence_transformers import SentenceTransformer

In [10]:
# Step 1: Generate embeddings using BAAI/bge-small-en model from HuggingFace
model = SentenceTransformer("all-MiniLM-L6-v2")

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

### Exploring embedding models

In [36]:
tokenizer = model.tokenizer

In [37]:
vocab = tokenizer.get_vocab()

In [38]:
for k, v in list(vocab.items())[:10]:
    print(k, v)

taiwanese 16539
starving 18025
level 2504
cry 5390
##pton 15857
loosened 22456
socialist 6102
utilities 16548
author 3166
sought 4912

In [39]:
sent = """non-technical book that shows how statistics"""

In [40]:
vocab['non']

2512

In [41]:
tokenizer.tokenize(sent)

['non', '-', 'technical', 'book', 'that', 'shows', 'how', 'statistics']

In [42]:
model.get_sentence_embedding_dimension()

384

In [43]:
model.encode(sent)[0:30]

array([-0.03008135, -0.05009521, -0.06271061,  0.04565006, -0.10417708,
       -0.04974668,  0.01520328,  0.07046074,  0.04057326,  0.11120791,
        0.00830345,  0.02517801,  0.05898906,  0.00799476, -0.02812008,
       -0.06369038, -0.01401609,  0.02919894,  0.04325732, -0.14875388,
       -0.02886812,  0.0128307 ,  0.074303  , -0.05063971,  0.04411563,
       -0.07871999,  0.01467848, -0.0442741 , -0.0124668 , -0.03063768],
      dtype=float32)

### Embedding the book summaries

In [44]:
# Generate embeddings for each summary
books_df['embedding'] = books_df['summaries'].map(lambda sentence: model.encode(sentence))

In [45]:
books_df.sample(5)

,book_name,summaries,embedding,similarity
316,Braiding Sweetgrass,offers some great ways for all of us to take better care of and be more grateful for our planet by explaining the way that Native Americans view and take care of it.,"[0.029431188, 0.11013349, 0.07023757, -0.004420528, 0.030356083, -0.058510635, 0.059210703, -0.07087464, -0.014445486, 0.04387651, 0.04040858, -0.016732078, -0.031494364, -0.046757333, -0.04623731, 0.052220795, -0.03079341, -0.010863813, -0.065005966, 0.06355426, -0.05512689, 0.048949555, 0.060917076, 0.09923085, -0.089415796, 0.036666557, -0.02899067, -0.0150444675, 0.043537352, -0.018595131, -0.04381399, 0.060896527, 0.063799806, 0.06340274, -0.15463302, 0.06536989, 0.035747904, -0.0669322...",0.058717
869,Uncertainty,"shows you that the condition of not knowing is nothing to fear, but the birthplace of innovation, which, if you embrace it while anchoring yourself, has an unlimited potential for growth, wealth and happiness.","[0.0767866, 0.032921877, -0.0036531833, 0.05443965, 0.09171969, 0.022682033, 0.057161182, -0.01282173, 0.010941389, 0.0022841205, 0.05365246, -0.0297438, 0.07131863, -0.12101785, -0.076388486, 0.022959827, -0.06358017, -0.06270797, -0.043983806, -0.059177745, -0.024708377, -0.010170447, -0.0056245406, 0.016556665, -0.03408344, 0.08590559, 0.042916406, -0.0028909568, 0.075800344, -0.015544114, 0.01651238, 0.022524353, -0.0028463774, -0.009049234, 0.089352235, -0.010079332, 0.033914115, 0.0259...",0.202655
354,Masters of Scale,"teaches entrepreneurs ways to open up a successful company and scale it from the grounds-up by going into detail about the right business practices, how to seize opportunities, and foster an organizational culture that encourages innovation and customer-centricity.","[0.06107183, 0.0035623026, -0.03893718, 0.005082484, -0.002924344, 0.01120894, 0.023454491, 0.015264472, -0.006375977, -0.023215652, 0.046740033, 0.11974307, -0.03830099, -0.008249081, 0.06317938, -0.007325657, -0.052556455, 0.06533694, -0.034879636, -0.08795686, -0.05315023, -0.09664355, 0.0110013755, 0.02505324, -0.10894411, 0.014103413, 0.07369902, 0.0055356333, 0.00485521, -0.085509524, 0.03161465, 0.02272834, 0.08253578, -0.0052000587, -0.014917278, 0.050022915, 0.036073253, -0.00499017...",0.342530
1027,Rework,"shows you that you need less than you think to start a business – way less – by explaining why plans are actually harmful, how productivity isn’t a result from working long hours and why hiring and seeking investors should be your absolute last resort.","[0.075905286, 0.08055371, 0.07814384, 0.030147856, 0.064015016, 0.06711252, -0.013692098, 0.08771742, -0.0098300325, -0.024102947, -0.10987752, 0.032589268, -0.07106363, -0.009034913, -0.006547599, -0.015841, 0.042014584, -0.07313802, -0.05946402, -0.049130972, 0.053727422, -0.037226457, -0.00012247042, 0.05910798, 0.0017388631, 0.043211702, 0.004244625, -0.0005203458, 0.055587362, 0.00365561, 0.0054584425, 0.045924824, 0.06482968, -0.03085239, 0.05449564, 0.030182173, 0.016605007, 0.0367295...",0.381984
1177,Fat For Fuel,explores the “,"[-0.023337528, 0.050009128, 0.040033378, 0.06286846, -0.0047622314, 0.031625263, 0.124415696, -0.09694068, 0.014075744, -0.005263652, -0.0076712132, -0.0015706646, -0.024781732, -0.009129035, 2.2426084e-05, 0.058108825, -0.04754452, 0.04726928, 0.012842156, -0.018364642, -0.03588859, -0.048184127, 0.024444629, -0.018259767, -0.013422463, 0.045546517, -0.005004444, -0.015901148, 0.15887055, -0.02283643, -0.07141804, 0.0824119, -0.005160756, 0.035417393, 0.046267554, 0.08929393, -0.005792014, ...",0.045404

## Finding topN similar books

In [46]:
from sklearn.metrics import pairwise_distances
from scipy.spatial.distance import cosine

In [47]:
books_sim = 1 - pairwise_distances( np.vstack(books_df['embedding'].to_numpy()), metric="cosine" )

In [48]:
books_sim_df = pd.DataFrame( books_sim )

In [49]:
books_sim_df

,0,1,2,3,4,5,6,7,8,9,...,1217,1218,1219,1220,1221,1222,1223,1224,1225,1226
0,1.000000,0.396789,0.280108,0.229071,0.279481,0.411384,0.402367,0.332052,0.265633,0.335035,...,0.236861,0.159036,0.193224,0.193629,0.294002,0.279639,0.287046,0.172833,0.437168,0.358787
1,0.396789,1.000000,0.266779,0.103441,0.208018,0.266748,0.266355,0.341875,0.282271,0.208028,...,0.183075,0.038439,0.080864,0.045930,0.249448,0.275041,0.324380,0.132472,0.444034,0.251680
2,0.280108,0.266779,1.000000,0.211138,0.355571,0.294086,0.211072,0.290829,0.239363,0.215984,...,0.110065,0.132435,0.115854,0.122064,0.079936,0.113936,0.295340,0.281162,0.287353,0.124289
3,0.229071,0.103441,0.211138,1.000000,0.515925,0.439304,0.233873,0.362537,0.327091,0.266109,...,0.230112,0.401782,0.420001,0.319358,0.246522,0.135552,0.440635,0.289590,0.307906,0.330853
4,0.279481,0.208018,0.355571,0.515925,1.000000,0.361580,0.274602,0.342572,0.368520,0.279203,...,0.179450,0.384806,0.380548,0.235430,0.280252,0.117542,0.320054,0.458088,0.293313,0.355029
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1222,0.279639,0.275041,0.113936,0.135552,0.117542,0.240332,0.212350,0.374164,0.171960,0.084567,...,0.148682,0.057140,0.199228,-0.017907,0.274967,1.000000,0.259205,0.078730,0.309932,0.067527
1223,0.287046,0.324380,0.295340,0.440635,0.320054,0.341518,0.237564,0.421541,0.411434,0.223612,...,0.259952,0.248273,0.268811,0.162067,0.183786,0.259205,1.000000,0.237930,0.498890,0.241490
1224,0.172833,0.132472,0.281162,0.289590,0.458088,0.187398,0.291065,0.237445,0.230616,0.163518,...,0.112589,0.150375,0.236480,0.055475,0.128672,0.078730,0.237930,1.000000,0.266237,0.185821
1225,0.437168,0.444034,0.287353,0.307906,0.293313,0.382567,0.282891,0.392067,0.268047,0.271651,...,0.197895,0.147412,0.252147,0.056902,0.342790,0.309932,0.498890,0.266237,1.000000,0.238231
1226,0.358787,0.251680,0.124289,0.330853,0.355029,0.292655,0.367069,0.249320,0.364803,0.379796,...,0.325751,0.242421,0.258464,0.303288,0.237650,0.067527,0.241490,0.185821,0.238231,1.000000

### Finding Similar Books

In [50]:
def get_similar_books( title, topN = 5 ):
    book_idx = books_df[books_df['book_name'] == title].index[0]
    books_df['similarity'] = books_sim_df.iloc[book_idx]
    top_n = books_df.sort_values( ["similarity"], ascending = False )[0:topN+1]
    #print( "Similar Movies to: ", )
    return top_n

In [51]:
get_similar_books( 'The Miracle of Mindfulness' )

,book_name,summaries,embedding,similarity
731,The Miracle of Mindfulness,teaches the ancient Buddhist practice of mindfulness and how living in the present will make you happier.,"[0.043977324, 0.060369458, -0.04075212, 0.020337781, -0.03391635, -0.017431594, 0.04923928, -0.07002196, 0.030952385, 0.023864334, 0.053883087, 0.07778906, -0.03576169, 0.0045336145, 0.050818782, -0.025068672, -0.05715388, 0.07341718, -0.030500727, -0.013006638, -0.039001666, 0.033726387, 0.035878148, 0.05033159, -0.07715294, 0.072594434, 0.03148723, -0.07526618, 0.07802809, 0.010375884, 0.058327224, -0.010838125, 0.03276472, -0.0024458638, -0.093665965, -0.0064969338, -0.06658898, -0.056234...",1.000000
718,Radical Acceptance,teaches how you can become more content and happy in your life by applying the principles of meditation and Buddhism.,"[0.05036906, 0.022219088, -0.024899168, 0.015659958, -0.0668243, 0.050159115, 0.03473323, -0.08002915, 0.016239535, 0.02636853, 0.034283057, 0.06939501, -0.020075575, -0.032921966, 0.08073523, -0.013790823, -0.021649968, 0.10032323, -0.046442606, -0.058184758, -0.055375937, 0.031843577, 0.010278574, 0.06950206, -0.08436739, 0.030896693, 0.021983223, -0.076352954, 0.09199907, 0.007806026, 0.07199313, 0.026375674, 0.055548564, -0.017330723, -0.12507093, 0.022277826, -0.04590875, -0.038167473, ...",0.814961
612,The Art of Living,"talks about living a peaceful life through meditation and gratitude, especially by using the Vipassana meditation technique and the philosophy behind Buddhism, which promotes developing a clearer vision of life and seeing things as they truly are.","[0.040577248, 0.04201716, -0.035066318, -0.01706462, -0.04830993, -0.00426358, 0.095602386, -0.1050119, 0.06078226, 0.011428683, 0.049979232, -0.0016760126, 0.009765565, -0.035360724, 0.006072571, 0.006838462, 0.011258984, 0.074769996, -0.04055523, 0.0020308373, -0.058581337, 0.024445016, -0.0058456245, 0.04357181, -0.06527495, 0.08519019, 0.012578007, -0.0034084541, 0.09037165, -0.037276573, 0.050088495, -0.0030932652, 0.023225907, 0.0012629176, -0.08265775, 0.08019465, -0.031788245, -0.002...",0.701163
410,That Sounds Fun,"uncovers the secrets of a happy life: mindfulness, love, joy, and a good dose of doing whatever makes us happy as often as we can, starting from simple, day-to-day activities, to much bigger life experiences that speak to our soul.","[-0.009061839, 0.08662473, 0.002003679, 0.04282847, 0.010520431, 0.038271006, 0.07749582, -0.075056806, 0.02536814, -0.003858995, 0.07542841, 0.02440577, -0.01669814, -0.011571323, 0.042664584, -0.024986899, -0.11219437, 0.030224659, -0.080647536, 0.005433448, -0.077982895, -0.03776725, -0.011240104, 0.07825012, -0.1167694, 0.043709874, 0.06151531, -0.022339726, -0.019936292, -0.014813912, 0.071904525, 0.0017951665, 0.07941498, -0.009198392, -0.027210696, 0.019977022, -0.08970568, -0.0371374...",0.644510
660,Unplug,"is your guide to utilizing meditation to enhance your brain, deal with stress, and become happier, explaining the basics of this practice, how to get started with it, and what science has to teach about its many benefits.","[0.045592654, -0.006102965, 0.04245939, 0.015723644, -0.05685259, 0.08809291, 0.06408002, -0.055719737, -0.03855104, -0.014458894, -0.015351719, 0.05864656, -0.0413291, -0.050214168, 0.05910332, 0.004195595, -0.028085055, 0.06141737, -0.03761151, -0.01160918, -0.0783037, -0.010750171, -0.02224284, 0.021417668, -0.07138144, 0.07080516, -0.027820436, -0.060199782, 0.040889196, 0.024392169, 0.06856561, 0.047938168, 0.0351306, -0.032393254, -0.034567352, -0.0042147865, -0.047470722, -0.05407394,...",0.628591
737,Inner Engineering,is a guide to creating a life of happiness by exploring your internal landscape of thoughts and feelings and learning to align them with what the universe tells you.,"[0.046232782, -0.006225705, -0.031999744, 0.043705128, -0.0045165983, 0.012529468, -0.014988564, -0.009222281, 0.026942138, 0.000975229, 0.013210096, 0.054346718, -0.00059136614, 0.0028269894, 0.03579149, -0.016279742, -0.075570814, -0.0062284064, -0.030957274, -0.0064994995, -0.015838498, 0.04406662, -0.09501375, 0.02214264, -0.08554044, 0.059135865, 0.05324716, 0.0049524554, 0.0026677535, -0.03150174, 0.094168164, 0.048791964, 0.047628634, -0.04971821, -0.0032633399, 0.046029996, -0.050290...",0.627253

In [52]:
get_similar_books( 'Get A Financial Life' )

,book_name,summaries,embedding,similarity
830,Get A Financial Life,shows those that are new to managing money how to do it confidently by explaining everything from debt and savings to insurance and investing.,"[0.047093544, 0.051483423, -0.019199703, 0.062272742, -0.005354381, 0.0053376798, 0.059674982, 0.009743588, -0.054319862, 0.073898956, 0.002266521, 0.016498161, 0.012399182, -0.01602161, 0.01719432, -0.0447213, -0.017446708, -0.022896515, -0.028098343, -0.05451456, 0.004561392, -0.09393661, 0.039281726, -0.008676599, 0.029697154, 0.052229974, 0.023931764, 0.056044463, 0.0064744256, 0.0041307122, 0.050805625, 0.010127408, 0.05805498, -0.020089231, -0.03957668, 0.070785195, -0.0230642, 0.09858...",1.000000
866,The Millionaire Next Door,shows you the simple spending and saving habits that lead to more cash in the bank than most people earn in their life while helping you avoid critical mistakes on your way to financial independence.,"[-0.009537516, 0.039845414, -0.046431787, 0.048608612, 0.044012435, -0.003606081, 0.10996671, 0.036673065, 0.017575795, -0.0114981085, 0.012274414, -0.0039300085, -0.015324681, -0.037045598, 0.030427989, -0.08801556, 0.0031616732, -0.06339549, -0.041718706, 0.009135829, -0.0026692466, -0.112013474, 0.012309414, 0.0768306, 0.0047930717, 0.015984014, -0.0027925374, 0.006961861, -0.0025294449, 0.0005399714, 0.07667866, 0.06393337, 0.06954507, -0.07818691, 0.0008735113, -0.0019443388, 0.04484025...",0.661513
832,Broke Millennial,shows those in their twenties and thirties how to manage their finances so that they can stop scraping by and instead begin to live more confidently when it comes to money.,"[0.016369436, 0.09722718, -0.00072548934, 0.0506817, 0.019502578, -0.001890464, 0.007268127, 0.0069581633, -0.037700757, 0.031602953, 0.0670808, -0.015058929, 0.025658522, -0.052371796, 0.016732022, -0.043298222, -0.048112806, -0.010302626, 0.053005736, -0.033283927, -0.03681042, -0.10629527, 0.05974951, -0.00037206622, 0.03049077, 0.062444046, -0.09891191, -0.01747598, -0.0010425717, 0.07067651, 0.15693995, 0.044563603, 0.051365204, -0.008390073, -0.033872303, -0.019857455, -0.00072617544, ...",0.651874
852,Dollars And Sense,explains why it’s so hard to manage money and teaches you how to combat false cues and natural desires so you can manage your dollars in better ways.,"[0.05497934, 0.043002725, -0.037627578, 0.07994843, -0.0008593809, -0.0025538136, 0.08726413, 0.023318924, 0.02984373, 0.06712426, -0.008822998, 0.017451905, -0.0176304, 0.0020112018, 0.05697425, -0.07714481, -0.0064834487, -0.016270686, -0.06643054, 0.031776942, 0.0450771, -0.0700665, 0.01207331, 0.0065047266, -0.0009769953, 0.067018114, -0.0498444, -0.04054092, -0.014434021, -0.03478366, 0.0863867, 0.081822775, 0.04643569, -0.043765746, -0.04028286, 0.0025635327, -0.044016704, 0.09113933, ...",0.641765
208,More Money Than God,"teaches us about the ins and outs of hedge funds, how those managing money makes a profit, and how you can learn from them and apply their techniques to your money management strategy.","[0.053132795, -0.045197565, -0.04058065, 0.041005857, 0.013576474, -0.021785585, 0.027664509, 0.031195007, -0.05276791, 0.05540657, -0.032817546, 0.0720824, -0.0056333737, -0.016585872, 0.01159674, -0.017041761, -0.03635371, -0.0009389602, -0.028652323, -0.02324001, 0.043006808, -0.07096934, 0.037095774, -0.0025047895, -0.06398874, -0.0032765677, 0.023792535, 0.012874898, -0.08657559, -0.024565192, 0.04014037, 0.0022719798, -0.02502678, -0.043676026, -0.08525988, 0.06673011, 0.0016307883, 0....",0.578497
697,The Latte Factor,teaches us how to overcome limiting beliefs about money and build our financial freedom through small daily choices.,"[0.0224733, 0.10840657, -0.065860674, 0.06697642, 0.031095652, 0.039169867, 0.057135295, -0.022181842, 0.057183802, 0.03453934, 0.024854112, 0.09547503, -0.03155443, -0.0242538, 0.016520191, -0.059745125, -0.080963045, 0.047889665, -0.013357765, -0.0069782105, -0.0045745047, -0.04366619, -0.0057079345, 0.047086686, 0.0019193445, 0.039570063, 0.072391205, -0.059615646, 0.036726993, -0.06526892, 0.060454972, 0.01776648, 0.029864833, -0.040637136, 0.022450523, 0.011211898, 0.074348964, 0.045875...",0.564691

In [53]:
get_similar_books( 'Permission Marketing' )

,book_name,summaries,embedding,similarity
1086,Permission Marketing,"explains why nobody pays attention to TV commercials and flyers anymore, and shows you how in today’s crowded market, you can cheaply start a dialogue with your ideal customer, build a relationship over time and sell to them much more effectively.","[-0.030076891, -0.018022835, 0.017643249, -0.039022245, 0.011061669, 0.06179028, 0.0381892, 0.06884139, 0.04724635, -0.08997964, -0.014048741, 0.08685047, -0.03507109, 0.016992804, 0.104498364, -0.071366765, 0.0450258, -0.03209907, -0.07433361, 0.007120011, -0.031645045, -0.015277831, -0.03797557, -0.0030352098, -0.05403092, -0.035263103, -0.0254799, 0.013801251, 0.0075066797, -0.003712439, 0.05347021, 0.07842415, 0.101765506, -0.01661341, -0.016232813, 0.020969007, -0.069372855, 0.015444755...",1.000000
1142,The Long Tail,"explains why the big commercial hit is dead, how businesses can and will generate most of their future revenue from a long tail of niche products, which serve even the rarest customer needs, and what you can do to embrace this idea today.","[-0.021558572, -0.074263714, 0.0009376337, -0.074445955, 0.06762239, 0.046283416, -0.006406229, 0.08469917, -0.01977086, -0.077788435, -0.02650536, 0.06141728, 0.015666177, -0.0015896908, 0.08591654, -0.014861975, 0.0044025667, -0.024217404, -0.07089648, -0.01346365, -0.015105312, 0.018307906, -0.02510171, 0.0009217009, -0.11206353, 0.006052959, -0.017921513, -0.05324292, -0.007329834, -0.055836152, 0.027704097, 0.09744755, 0.02903068, -0.0070865923, 0.023297215, -0.00015076355, -0.029898774...",0.610961
931,Epic Content Marketing,shows why traditional methods for selling like TV and direct mail are dead and how creating content is the new future of advertising because it actually grabs people’s attention by focusing on what they care about instead of your product.,"[-0.018247742, -0.07733424, 0.019648977, -0.024510875, 0.08285824, 0.02858335, -0.050018016, 0.0482326, 0.008074597, -0.047778886, -0.0047820583, 0.11049994, -0.019245783, 0.005509617, 0.051240265, -0.052823525, 0.03964334, -0.08599285, -0.031803805, 0.0037298917, 0.045756776, 0.036747213, 0.0118062245, -0.0029037, -0.017090417, -0.033031803, -0.04751458, -0.04405505, 0.033792064, -0.04103137, 0.010960794, 0.10099079, 0.033132277, -0.028805302, -0.066833176, 0.02669233, -0.0057819095, -0.043...",0.579648
1088,Purple Cow,"explains why building a great product and advertising the heck out of it simply doesn’t cut it anymore and how you can build something that’s so remarkable people have to share it, in order to succeed in today’s crowded post-advertising world.","[-0.017602151, -0.0009882798, 0.025963698, -0.050047934, 0.12011608, 0.008536543, 0.05461069, 0.07618103, -0.01960091, -0.05813871, -0.037548386, 0.04167475, 0.02012879, -0.00823857, 0.031226886, -0.0014111716, -0.0019881998, -0.062047005, -0.07186341, -0.08395644, 0.07425073, 0.0012193429, 0.0043972037, 0.048593376, -0.06221582, 0.039220557, -0.026271224, -0.0129918195, 0.040553655, -0.057114888, 0.042564854, 0.019350344, 0.09867892, -0.022207689, 0.007858331, 0.033683665, -0.044208627, -0....",0.577623
1126,This Is Marketing,"argues that marketing success in today’s world comes from focusing more on the needs, values, and desires of our target audience, rather than spamming as many people as possible with our message.","[0.021531027, -0.0069928607, -0.0071949516, -0.021298215, 0.06997249, 0.0033442006, 0.12523745, 0.013181568, 0.025552941, -0.14000848, 0.039742075, 0.01311541, 0.077597044, -0.029995695, 0.13576855, -0.033373017, 0.05219282, -0.018406188, -0.071594544, 0.010958572, -0.06683712, -0.007039217, -0.0008506012, 0.030236293, -0.12841378, -0.077462554, -0.042098537, -0.025428707, -0.008378053, -0.031613763, 0.037909936, 0.038204167, 0.066425934, 0.01868009, 0.053969104, 0.04837355, -0.07059402, -0....",0.575825
1132,The Fortune Cookie Principle,"explains why a great product or service isn’t enough, how you can tell a compelling story about your brand and why that’s the most important aspect of running a business today.","[0.022747634, 0.02911998, 0.04482099, -0.07860735, 0.053295635, 0.025894986, 0.039052177, 0.09677942, -0.0011926565, -0.054891642, -0.024087146, 0.09490093, 0.011908708, -0.0020536664, 0.052389715, -0.06703156, 0.07061496, -0.05651549, -0.09647859, -0.05160323, 0.08005687, -0.039464854, 0.024676278, 0.0853904, -0.11195087, 0.042205308, 0.014462344, 0.009545132, -0.03881599, -0.100195825, -0.04312641, 0.038978226, 0.06593384, -0.05899833, 0.028070534, 0.0014222799, 0.0010388559, -0.002432474,...",0.552454